tournament:
    resource: "@TournamentBundle/Resources/config/routing.yml"
    prefix:   /

guide:
    resource: "@GuideBundle/Resources/config/routing.yml"
    prefix:   /

news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /

team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: "@GalleryBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation
